version: '3.8'  # Optional but good to specify  
services:  
  app:  
    build:  
      context: .  # Ensure this is where your Dockerfile is located  
      dockerfile: Dockerfile  # Ensure this matches your actual Dockerfile name  
    ports:  
      - "80:80"  # Bind host port to container port