services:  
  app:  
    build:  
      context: .  # Path to your Dockerfile directory  
      dockerfile: Dockerfile  # Adjust if your Dockerfile is named something else  
    ports:  
      - "80:80"  # Map the ports